version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/HTML-Code-Demos/
hooks:
  BeforeInstall:
    - location: code/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: code/restart_server
      timeout: 300
      runas: root
